### ISSUE TITLE
java.io.IOException: Cannot run program "yarn" (in directory "../frontend"): error=2

### ISSUE THREAD

**Issue by dhanugupta** [geowarin/boot-react#48]
Is it known issue??
./gradlew bootRun
 
2018-05-30 22:09:45.922 ERROR 25447 --- [  restartedMain] org.zeroturnaround.exec.ProcessExecutor  : Could not start process:

java.io.IOException: Cannot run program "yarn" (in directory "../frontend"): error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) ~[na:1.8.0_171]
        at org.zeroturnaround.exec.ProcessExecutor.invokeStart(ProcessExecutor.java:977) [zt-exec-1.9.jar:na]
        at org.zeroturnaround.exec.ProcessExecutor.startInternal(ProcessExecutor.java:950) [zt-exec-1.9.jar:na]
        at org.zeroturnaround.exec.ProcessExecutor.execute(ProcessExecutor.java:890) [zt-exec-1.9.jar:na]
        at react.dev.YarnRunner.yarnCheck(YarnRunner.java:67) [main/:na]
        at react.dev.YarnRunner.startFrontend(YarnRunner.java:55) [main/:na]
        at react.dev.YarnRunner.run(YarnRunner.java:39) [main/:na]

**Comment by dhanugupta** [comment]
got it resolved by installing yarn locally on mac..

**Comment by dhanugupta** [comment]
looks like this issue coming up when i am try to run spring boot from eclipse IDE.. any solution to fix it??

**Comment by shubhamp861** [comment]
May be a problem with the package of yarn, try this command in cmd = "npm install -g yarn"
